apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: 1.12.1
    helm:
      releaseName: external-dns
      values: |
        serviceAccount:
          create: true
          name: external-dns
          annotations:
            iam.gke.io/gcp-service-account: external-dns-kubefirst2@test-gitops-kubefirst.iam.gserviceaccount.com
        domainFilters:
          - kubefirst.shankyjs.com
        provider: google
    chart: external-dns
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
