apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: https://runatlantis.github.io/helm-charts
    chart: atlantis
    targetRevision: 4.11.2
    helm:
      values: |-
        statefulSet:
          annotations:
            secret.reloader.stakater.com/reload: "atlantis-secrets"
        atlantisUrl: https://atlantis.kubefirst.shankyjs.com
        orgAllowlist: github.com/shankyjs-playground/*
        hidePrevPlanComments: true
        serviceAccount:
          create: true
          mount: true
          annotations:
            iam.gke.io/gcp-service-account: atlantis-kubefirst2@test-gitops-kubefirst.iam.gserviceaccount.com
        resources:
          limits:
            cpu: 400m
            memory: 1Gi
          requests:
            cpu: 400m
            memory: 512Mi
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          path: /
          host: atlantis.kubefirst.shankyjs.com
          ingressClassName: "nginx"
          tls:
            - secretName: atlantis-tls
              hosts:
                - atlantis.kubefirst.shankyjs.com
        loadEnvFromSecrets:
          - atlantis-secrets
        repoConfig: |
          ---
          repos:
          - id: github.com/shankyjs-playground/*
            workflow: default
            allowed_overrides: [apply_requirements]
            apply_requirements: [mergeable]
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: atlantis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
